Experimental/classes stage iii
punditcommunity/pundit-matchers pull request #81
Opened 2023-05-16 17:11 UTC by tagliala

@chrisalley if you want to take an overall review

I would check messages and, if you are using it actively, test this branch against a large codebase

2023-05-20 04:01 UTC, chrisalley requested changes
I've tested this branch against a codebase with 392 policy tests. There were no failures. (Note: the specs don't use `permit_mass_assignment_of` extensively, and do not use `not_to` since that was never supported.)

Overall I like your approach. The internals have been simplified  and the use of "helper matchers" reduces the number of files that we need to have.

Great job!

2023-05-20 09:58 UTC, tagliala commented on CHANGELOG.md
> +- `not_to permit_mass_assignment_of` (with multiple attributes)
new, to review

I've also eliminated a breaking change for #35 (I will do it separately with better support for specific aliases)

2023-05-20 10:08 UTC, tagliala commented on lib/pundit/matchers/base_matcher.rb
> +        Instead use `expect().%<suggested_matcher>s`'
I'll remove the suggestion because no one can understand what `not_to forbid_all_actions` means

2023-05-21 01:18 UTC, chrisalley commented
There's some solid work here; much appreciated. Since this is already a big set of changes, it would be good to have the branch finalised for a 3.0.0 release. It can be used as the basis for smaller releases in the future.

2023-05-21 08:14 UTC, tagliala commented
If you can merge this, I will incrementally

- Add support for multiple user aliases (easy **breaking change** in case of `user_alias` customization) #35 
- Add support for nested attributes #7

2023-05-23 08:08 UTC, merged